FROM python:3.10-slim

WORKDIR /app

# System dependencies for PyTorch & RDKit
RUN apt-get update && apt-get install -y \
    libxrender1 libxext6 libexpat1 \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
RUN pip install --no-cache-dir --default-timeout=1800 \
    "numpy<2" \
    fastapi uvicorn pydantic \
    torch --extra-index-url https://download.pytorch.org/whl/cpu \
    torch_geometric \
    rdkit

COPY model.py main.py pharma_gnn_weights_universal.pt* /app/

EXPOSE 1234

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "1234"]
