version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "1234:1234"
    volumes:
      - ./pharma_gnn_weights_universal.pt:/app/pharma_gnn_weights_universal.pt
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:1234/api/predict
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
